all:
  hosts:
    master-1:
      ansible_host: 89.169.151.16
      access_ip: 89.169.151.16
      ip: 10.0.1.25
      ansible_user: ubuntu
    worker-1:
      ansible_host: 158.160.67.107
      access_ip: 158.160.67.107
      ip: 10.0.2.30
      ansible_user: ubuntu
    worker-2:
      ansible_host: 158.160.171.160
      access_ip: 158.160.171.160
      ip: 10.0.3.14
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        master-1:
    kube_node:
      hosts:
        master-1:
        worker-1:
        worker-2:
    etcd:
      hosts:
        master-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node: